# Generated by Django 3.2.8 on 2021-10-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20211021_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleImage',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Makaleye fotoğraf ekleyin.'),
        ),
    ]
